trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - name: connectionString
    value: $(connectionString)
  - name: startupProjectPath
    value: './src/DemoWebApi.Api/DemoWebApi.Api.csproj'
  - name: projectPath
    value: './src/DemoWebApi.Infrastructure/DemoWebApi.Infrastructure.csproj'
  - name: dotNetVersion
    value: '8.x'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Migration Project'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              version: $(dotNetVersion)

          - script: |
              dotnet restore $(projectPath)
              dotnet restore $(startupProjectPath)
              dotnet build $(projectPath) --configuration Release
              dotnet build $(startupProjectPath) --configuration Release
            displayName: 'Restore and Build'

  - stage: ApplyMigration
    displayName: 'Apply Migrations'
    dependsOn: Build
    jobs:
      - job: ApplyMigrations
        displayName: 'Apply EF Core Migrations'
        steps:
          - script: |
              dotnet tool install --global dotnet-ef
              dotnet ef database update --project $(projectPath) --startup-project $(startupProjectPath) --connection "$(connectionString)"
            displayName: 'Apply Migrations'