trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  connectionStringStaging: $(connectionStringInPipelineStaging)
  connectionStringProd: $(connectionStringInPipelineProd)
  startupProjectPath: './src/DemoWebApi.Api/DemoWebApi.Api.csproj'
  projectPath: './src/DemoWebApi.Infrastructure/DemoWebApi.Infrastructure.csproj'
  dotNetVersion: '8.x'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build projects to run migrations'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              version: $(dotNetVersion)

          - script: |
              dotnet restore $(projectPath)
              dotnet restore $(startupProjectPath)
              dotnet build $(projectPath) --configuration Release
              dotnet build $(startupProjectPath) --configuration Release
            displayName: 'Restore and Build'

  - stage: ApplyMigrationsToStaging
    displayName: 'Apply migrations to Staging'
    dependsOn: Build
    jobs:
      - template: template-migration.yml
        parameters:
          environment: 'staging'
          connectionString: $(connectionStringStaging)
          projectPath: $(projectPath)
          startupProjectPath: $(startupProjectPath)
          
  - stage: ApplyMigrationsToProduction
    displayName: 'Apply migrations to Production'
    dependsOn: ApplyMigrationsToStaging
    condition: false
    jobs:
      - template: template-migration.yml
        parameters:
          environment: 'production'
          connectionString: $(connectionStringProd)
          projectPath: $(projectPath)
          startupProjectPath: $(startupProjectPath)