trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'rm-service-connection'
  dotNetVersion: '8.x'
  artifactName: 'demowebpi'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - template: restore-build-test.yml
        parameters:
          dotNetVersion: $(dotNetVersion)
          artifactName: $(artifactName)

  - stage: DeployToStaging
    displayName: 'Deploy to Staging'
    dependsOn: BuildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: deploy.yml
        parameters:
          environment: 'staging'
          azureSubscription: $(azureSubscription)
          appServiceName: 'demo-web-api-staging'
          artifactName: $(artifactName)
          

  - stage: DeployToProduction
    displayName: 'Deploy to Production'
    dependsOn: DeployToStaging
    condition: false
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: deploy.yml
        parameters:
          environment: 'production'
          azureSubscription: $(azureSubscription)
          appServiceName: 'demo-web-api-production'
          artifactName: $(artifactName)
