trigger:
  - master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'dl-service-connection-name'
  solution: '**/*.sln'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - template: restore-build-test.yml
        parameters:
          solution: $(solution)
          buildConfiguration: $(buildConfiguration)

  - stage: DeployToStaging
    displayName: 'Deploy to Staging'
    dependsOn: BuildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: deploy.yml
        parameters:
          environment: 'staging'
          azureSubscription: $(azureSubscription)
          appServiceName: 'demo-web-api-staging'

#  - stage: DeployToProduction
#    displayName: 'Deploy to Production'
#    dependsOn: BuildAndTest
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#    jobs:
#      - template: deploy.yml
#        parameters:
#          environment: 'production'
#          azureSubscription: $(azureSubscription)
#          appServiceName: 'demo-web-api-prod'