parameters:
  environment: ''
  azureSubscription: ''
  appServiceName: ''
  dotNetVersion: ''

jobs:
  - job: Deploy
    displayName: 'Deploy to Azure App Service (${parameters.environment})'
    steps:
      - task: ArchiveFiles@2
        displayName: 'Archive Build Artifacts'
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/build.zip'
          artifactName: 'drop'

      - task: AzureWebApp@1
        displayName: 'Deploy to Azure App Service (${parameters.environment})'
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          appType: 'webApp'
          appName: ${{ parameters.appServiceName }}
          package: '$(Pipeline.Workspace)/drop/build.zip'